### ISSUE TITLE
option -ft nucs causes error

### ISSUE THREAD

**Issue by bikdm12** [thedamlab/rodeo2#2]
I am running rodeo with accession number WP_011847902.1 as a query
with fetch type "cds" it is doing nice
but with "nucs" it crashes
If WP_011847902.1 is a part of a list in text file its presence ruins the whole run

**Comment by bkille** [comment]
Can you provide the output that it crashes with?

**Comment by bikdm12** [comment]
I tried it on another machine and it surprisingly doesn't crash completely
Instead it just returns error
```2018-08-02 14:37:59,962 - entrez_utils - INFO - Fetching WP_011847902.1 data from GenBank.
2018-08-02 14:38:19,988 - entrez_utils - ERROR - Failed to fetch record for WP_011847902.1.
2018-08-02 14:38:19,988 - entrez_utils - ERROR - <urlopen error [Errno -3] Temporary failure in name resolution>
2018-08-02 14:38:50,017 - entrez_utils - ERROR - Failed to fetch record for WP_011847902.1.
2018-08-02 14:38:50,017 - entrez_utils - ERROR - <urlopen error [Errno -3] Temporary failure in name resolution>
2018-08-02 14:39:25,463 - entrez_utils - ERROR - Failed to fetch record for WP_011847902.1.
2018-08-02 14:39:25,464 - entrez_utils - ERROR - <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
2018-08-02 14:39:25,467 - rodeo_main - INFO - Writing output for query #1.	WP_011847902.1
2018-08-02 14:39:25,467 - rodeo_main - ERROR - For WP_011847902.1:	Any response failure from Entrez database (error on database side)
2018-08-02 14:39:25,468 - rodeo_main - ERROR - No valid results. Input may be invalid or Genbank may not be responding

**Comment by bikdm12** [comment]
But with a list of accession numbers it produces
`````` 2018-08-02 14:02:17,501 - entrez_utils - INFO - Fetching WP_011847902.1 data from GenBank.
2018-08-02 14:02:33,607 - entrez_utils - INFO - Parsing WP_011847902.1 handle.
2018-08-02 14:03:44,044 - entrez_utils - INFO - Fetching WP_000351266.1 data from GenBank.
2018-08-02 14:03:44,210 - record_processing - INFO - Worker process 1 is processing WP_011847902.1
2018-08-02 14:03:44,309 - rodeo_main - INFO - Writing output for query #1.	WP_011847902.1
Traceback (most recent call last):
  File "rodeo_main.py", line 369, in <module>
    __main__()
  File "rodeo_main.py", line 312, in __main__
    main_html_generator.write_record(main_html, master_conf, record)
  File "/home/gyrase/datatank/rodeo2-master/main_html_generator.py", line 332, in write_record
    draw_orf_diagram(main_html, record, master_conf['general'])
  File "/home/gyrase/datatank/rodeo2-master/main_html_generator.py", line 173, in draw_orf_diagram
    bsc_start = min(record.CDSs[0].start, record.CDSs[0].end)
IndexError: list index out of range
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gyrase/datatank/rodeo2-master/record_processing.py", line 111, in process_record_worker
    record = unprocessed_records_q.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
2018-08-02 14:06:47,223 - entrez_utils - ERROR - Failed to fetch record for WP_000351266.1.
2018-08-02 14:06:47,223 - entrez_utils - ERROR - <urlopen error [Errno -3] Temporary failure in name resolution>
Sending timeout signal...
2018-08-02 14:08:44,044 - entrez_utils - ERROR - Timeout while reaching genbank for WP_000351266.1.
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gyrase/datatank/rodeo2-master/record_processing.py", line 140, in fill_request_queue
    unprocessed_records_q.put(ErrorReport(query, error_message))
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

**Comment by bkille** [comment]
Okay, I'll take a look at this. In the first post it seems like an issue with either your computers network connection or Genbank.

**Comment by bikdm12** [comment]
Thank you for the reply!
-fn option helped. 
Indeed, I was confused, I thought that this option refers only to cds ft type and for nucs there is -fd.
Sorry for not informative report. This is the first time I'm writing an issue.
